CREATE SCHEMA IF NOT EXISTS FLEET;

CREATE TABLE IF NOT EXISTS FLEET.PERSONS
(
	id BIGINT NOT NULL IDENTITY PRIMARY KEY,
	card_num VARCHAR(20) UNIQUE,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255),
	address VARCHAR (512)
);

CREATE TABLE IF NOT EXISTS FLEET.PHONES
(
	phone VARCHAR(9) NOT NULL PRIMARY KEY,
	person BIGINT NOT NULL,
	FOREIGN KEY (person) REFERENCES FLEET.PERSONS(id)
);

CREATE TABLE IF NOT EXISTS FLEET.INVOICES
(
	id BIGINT NOT NULL IDENTITY PRIMARY KEY,
	phone VARCHAR(9) NOT NULL,
	validity_date DATE NOT NULL,
	bill INT NOT NULL,
	membership_fee INT NOT NULL,
	FOREIGN KEY(phone) REFERENCES FLEET.PHONES(phone)
);

CREATE TABLE IF NOT EXISTS FLEET.PAYMENTS
(
	id BIGINT NOT NULL IDENTITY PRIMARY KEY,
	phone VARCHAR(9) NOT NULL,
	validity_date DATE NOT NULL,
	payment_value INT NOT NULL,
	FOREIGN KEY(phone) REFERENCES FLEET.PHONES(phone)
);

CREATE TABLE IF NOT EXISTS FLEET.STATIC_INFO
(
	validity_date DATE NOT NULL PRIMARY KEY, -- to keep track previous values, and this is also the primary key then
	default_membership_fee INT NOT NULL,
	membership_fee_threshold INT NOT NULL
);